### ISSUE TITLE
"ChkTeX does not handle lines over 1024 bytes correctly"

### ISSUE THREAD

**Issue by NickRSearcy** [SublimeLinter/SublimeLinter-chktex#13]
This is likely related to #4 . 

Full error message is

```
Error: chktex: WARNING -- ChkTeX does not handle lines over 1024 bytes correctly. Some errors and line numbers may be wrong in this file.
Error: chktex: WARNING -- ChkTeX does not handle lines over 1024 bytes correctly.  Some errors and line numbers may be wrong in this file.
    at parameters.exit (/Users/nrs/.atom/packages/linter-chktex/node_modules/atom-linter/lib/helpers.js:58:20)
    at triggerExitCallback (/opt/homebrew-cask/Caskroom/atom/1.0.14/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at /opt/homebrew-cask/Caskroom/atom/1.0.14/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:222:18
    at Socket.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.0.14/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

I can run chktex on the file in the terminal fine. I've uploaded the file to [a gist](https://gist.github.com/NickRSearcy/a036cb1974b5adaf356bb30aa30905e8)

**Comment by adamaltmejd** [comment]
Seems to be a ChkTeX problem: https://savannah.nongnu.org/bugs/?37013

Perhaps you could just use some linebreaks?

**Comment by NickRSearcy** [comment]
ChkTeX runs fine on the same file in the terminal, though

**Comment by adamaltmejd** [comment]
Huh wait? Are you using this with Atom? Think this is the relevant repo in that case: https://github.com/nscaife/linter-chktex

**Comment by braver** [comment]
This is not atom.
